name: ionic
services:
  mysql-ionic:
    container_name: mysql-ionic
    image: mysql:8
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=ionic
    env_file:
      - .env
    volumes:
      - /media/ionic-mysql:/var/lib/mysql

  bot:
    container_name: bot
    restart: always
    build:
      context: ./
      target: bot
    environment:
      - MYSQL_HOSTNAME=mysql-ionic
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ionic
    env_file:
      - .env

  web:
    container_name: web
    restart: always
    build:
      context: ./
      target: web
    ports:
      - 7777:7777
    environment:
      - MYSQL_HOSTNAME=mysql-ionic
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ionic
    env_file:
      - .env
